# Generated by Django 2.2.2 on 2019-06-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Endereço de Email')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/uploads')),
                ('is_active', models.BooleanField(default=True)),
                ('first_access', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
